name: CI Checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          git clone https://github.com/espressif/esp-idf.git
          cd esp-idf
          git submodule update --init --recursive
          cd components/mbedtls/mbedtls
          git am ../../../../patch/mbedtls/*
          cd ../../..
          ./install.sh
          . export.sh
          cd ../main/lib/libwebsockets
          git am ../../../patch/libwebsockets/*
          cd ../libsrtp
          git am ../../../patch/libsrtp/*
          cd ../../..
          idf.py build

